In [2]:
import numpy as np
import math

### expand_dims
##### Convert a 1D array into a column vector.

In [4]:
a = np.random.randint(0,100,10)
a

array([11, 19, 30, 36, 45, 12, 45, 44, 38, 71], dtype=int32)

In [7]:
np.expand_dims(a,axis=1)

array([[11],
       [19],
       [30],
       [36],
       [45],
       [12],
       [45],
       [44],
       [38],
       [71]], dtype=int32)

### Use of Where Function
##### Find indices where array elements are greater than a given value.

In [9]:
np.where(a>30)    # it will result only the index numbers

(array([3, 4, 6, 7, 8, 9]),)

In [10]:
a[np.where(a>34)]   # it will result the values 

array([36, 45, 45, 44, 38, 71], dtype=int32)

##### Replace values greater than a threshold using where.   (Condition , True , False)

In [22]:
np.where(a>25, 'Yes', 'No')

In [28]:
x = np.where(a>50, a, 0)
x

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0, 71], dtype=int32)

In [33]:
arr = np.where(a>25, a, 0) | x
arr

array([ 0,  0, 30, 36, 45,  0, 45, 44, 38, 71], dtype=int32)

##### Use where to filter rows from a 2D array.

In [37]:
arr = np.random.randint(0,25,24).reshape(4,6)
arr

array([[ 2,  8, 10, 14,  2,  1],
       [13,  0, 11, 19, 20,  5],
       [ 0, 21, 14,  9, 11,  6],
       [22,  6, 21, 24,  4,  9]], dtype=int32)

In [48]:
z = np.where(arr>20 , 0 , arr)
z

array([[ 2,  8, 10, 14,  2,  1],
       [13,  0, 11, 19, 20,  5],
       [ 0,  0, 14,  9, 11,  6],
       [ 0,  6,  0,  0,  4,  9]], dtype=int32)

### Argmax (argument of the maximum)

In [43]:
a=np.argmax(arr)
a

np.int64(21)

In [45]:
a=np.argmin(arr)
a

np.int64(7)

### Cumsum (cumulative sum)

In [49]:
np.cumsum(z)

array([  2,  10,  20,  34,  36,  37,  50,  50,  61,  80, 100, 105, 105,
       105, 119, 128, 139, 145, 145, 151, 151, 151, 155, 164])

In [51]:
np.cumsum(z , axis=0)

array([[ 2,  8, 10, 14,  2,  1],
       [15,  8, 21, 33, 22,  6],
       [15,  8, 35, 42, 33, 12],
       [15, 14, 35, 42, 37, 21]])

### Percentile

In [62]:
arr = ([10,10,20,25,50,30,35,80,83,97,54,76,86,55])
arr

[10, 10, 20, 25, 50, 30, 35, 80, 83, 97, 54, 76, 86, 55]

In [63]:
np.percentile(arr, 100)

np.float64(97.0)

In [64]:
np.percentile(arr,75)

np.float64(79.0)

In [65]:
np.percentile(arr ,0)

np.float64(10.0)

### Histogram

In [69]:
np.histogram(arr,bins=[0,20,40,60,80])

(array([2, 4, 3, 2]), array([ 0, 20, 40, 60, 80]))

### Corrcoef

In [72]:
np.corrcoef(arr)

np.float64(1.0)

### np.isin  (It wil check whether it is or not)

In [74]:
items = [10,20,30,40,50]
np.isin(arr,items)

array([ True,  True,  True, False,  True,  True, False, False, False,
       False, False, False, False, False])

In [75]:
arr

[10, 10, 20, 25, 50, 30, 35, 80, 83, 97, 54, 76, 86, 55]

In [76]:
np.flip(arr)

array([55, 86, 76, 54, 97, 83, 80, 35, 30, 50, 25, 20, 10, 10])

### PUT (it is use to modify that particular value using the index value of it)

In [84]:
arr = np.linspace(1,100,10)
arr

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [89]:
np.put(arr, [0,1], [222, 333])
arr

array([222., 333.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

### np.delete  (it has to be by putting its index number to remove that particular value)

In [91]:
np.delete(arr,0) 

array([333.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [98]:
# Use 'a_min' and 'a_max' instead of 'arr_min' and 'arr_max'
new_arr = np.clip(arr, a_min=25, a_max=100)
new_arr

array([100., 100.,  25.,  34.,  45.,  56.,  67.,  78.,  89., 100.])