In [3]:
import numpy as np
import math
from numpy import pi

### Method of creating the the array using the numpy

In [93]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
a.shape

(2, 3)

In [94]:
b = np.array([1,2,3,4])
print(b)
b.shape

[1 2 3 4]


(4,)

### Excessing the values of the Arrays


In [95]:
a[0][1]


np.int64(2)

In [96]:
b[0]=10
b

array([10,  2,  3,  4])

In [97]:
b[:2]

array([10,  2])

In [98]:
c= np.array([[1,2,3,4,5],
             [5,6,7,8,9],
             [9,8,7,6,5]
            ])

### Knowing about the shape of the array

In [99]:
c.shape


(3, 5)

In [100]:
c.ndim

2

In [101]:
len(c.shape) == c.ndim

True

In [102]:
len(c.shape)

2

In [103]:
c.size

15

In [104]:
import math


In [105]:
math.prod(c.shape)

15

In [106]:
c.size == math.prod(c.shape)

True

In [107]:
c.dtype

dtype('int64')

### Creating the Zeroes/ones of the arrays 

In [108]:
d = np.zeros(5)
d

array([0., 0., 0., 0., 0.])

In [109]:
np.ones(4)

array([1., 1., 1., 1.])

In [110]:
np.ones((2, 3, 4), dtype=np.int64)


array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [111]:
np.ones((2, 3, 4), dtype=np.float16)

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float16)

In [112]:
np.ones((2, 4, 3), dtype=np.complex64)


array([[[1.+0.j, 1.+0.j, 1.+0.j],
        [1.+0.j, 1.+0.j, 1.+0.j],
        [1.+0.j, 1.+0.j, 1.+0.j],
        [1.+0.j, 1.+0.j, 1.+0.j]],

       [[1.+0.j, 1.+0.j, 1.+0.j],
        [1.+0.j, 1.+0.j, 1.+0.j],
        [1.+0.j, 1.+0.j, 1.+0.j],
        [1.+0.j, 1.+0.j, 1.+0.j]]], dtype=complex64)

### Creating the empty array (by Randon Values)

In [113]:
np.empty(3)

array([0., 0., 0.])

### Arrange : it can create the array in specific distance manner

In [114]:
e = np.arange(8)
e

array([0, 1, 2, 3, 4, 5, 6, 7])

In [115]:
f = np.arange(3,12,1.5)
f

array([ 3. ,  4.5,  6. ,  7.5,  9. , 10.5])

In [116]:
i = np.arange(20).reshape(4, 5)
i

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

### np.linspace() to create an array with values that are spaced linearly in a specified interval:

In [117]:
g= np.linspace(3,15, num=7)
g

array([ 3.,  5.,  7.,  9., 11., 13., 15.])

In [121]:
x = np.linspace(0, 4, 4)
x

array([0.        , 1.33333333, 2.66666667, 4.        ])

In [126]:
np.linspace(0, 100 * pi, 5)        # useful to evaluate function at lots of points


array([  0.        ,  78.53981634, 157.07963268, 235.61944902,
       314.15926536])

In [133]:
x = np.linspace(0, 2 * pi, 10)        # useful to evaluate function at lots of points
f = np.sin(x)
x
f

array([ 0.00000000e+00,  6.42787610e-01,  9.84807753e-01,  8.66025404e-01,
        3.42020143e-01, -3.42020143e-01, -8.66025404e-01, -9.84807753e-01,
       -6.42787610e-01, -2.44929360e-16])

In [136]:
np.linspace(0, 2, 9).reshape(3, 3)

array([[0.  , 0.25, 0.5 ],
       [0.75, 1.  , 1.25],
       [1.5 , 1.75, 2.  ]])

In [137]:
np.linspace(0, 2*pi, 9).reshape(3, 3)

array([[0.        , 0.78539816, 1.57079633],
       [2.35619449, 3.14159265, 3.92699082],
       [4.71238898, 5.49778714, 6.28318531]])

In [130]:
h = np.ones(4, dtype=np.int64)
h

array([1, 1, 1, 1])

In [131]:
i.itemsize

8

In [132]:
i.size

20

### The type of the array can also be explicitly specified at creation time:

In [ ]:
np.array([[1, 2], [3, 4]], dtype=complex)

In [ ]:
np.array([[1, 2], [3, 4]], dtype=float)

In [ ]:
np.array([[1, 2], [3, 4]], dtype=int)

In [ ]:
np.zeros((3, 4))

In [152]:
np.linspace(1,25,24).reshape(6,4)

array([[ 1.        ,  2.04347826,  3.08695652,  4.13043478],
       [ 5.17391304,  6.2173913 ,  7.26086957,  8.30434783],
       [ 9.34782609, 10.39130435, 11.43478261, 12.47826087],
       [13.52173913, 14.56521739, 15.60869565, 16.65217391],
       [17.69565217, 18.73913043, 19.7826087 , 20.82608696],
       [21.86956522, 22.91304348, 23.95652174, 25.        ]])

In [151]:
np.arange(1,25).reshape(6,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [154]:
np.arange(1,25,3).reshape(4,2)

array([[ 1,  4],
       [ 7, 10],
       [13, 16],
       [19, 22]])

### Basic Arithmetic Operations 

In [156]:
a1 = np.array([20,30,45,56,89])

In [158]:
a2 = np.array([1,2,3,4,5])

In [159]:
a1-a2

array([19, 28, 42, 52, 84])

In [160]:
2*(a1-a2)

array([ 38,  56,  84, 104, 168])

In [163]:
(np.sin(a1)**2)*10 

array([8.33469031, 9.7620649 , 7.24036808, 2.72015448, 7.39719383])

In [164]:
(np.sin(a1)**2)*10  < 8 

array([False, False,  True,  True,  True])

#### Here we have the martix oprations

In [172]:
a3 = np.array([
    [2,3,4],
    [3,4,5],
    [5,6,7]
])

a4 = np.arange(12).reshape(3,4)
print(a3)
print(a4)

[[2 3 4]
 [3 4 5]
 [5 6 7]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [168]:
a3@a4                     # matrix product

array([[ 44,  53,  62,  71],
       [ 56,  68,  80,  92],
       [ 80,  98, 116, 134]])

In [174]:
a3.dot(a4)                     # another matrix product

array([[ 44,  53,  62,  71],
       [ 56,  68,  80,  92],
       [ 80,  98, 116, 134]])

### Random Function 

In [11]:
# create instance of default random number generator

rg = np.random.default_rng(4)  
print(rg)

Generator(PCG64)


In [188]:
rg.random((2,3))

array([[0.58886497, 0.09348256, 0.14646923],
       [0.69389313, 0.32261722, 0.75528723]])

### Tagda Questions

In [6]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [10]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])